### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by BjornB2**
- Removed imgur code (wasn't working for me)
- Added a download button which downloads a jpg version of the canvas with a filename including date.
- Removed two of the 3 sample photos.
- Changed background to white.

### CODE REVIEW

**Comment by mofosyne** [comment]
Thanks mate! It works and looks good!

**Comment by mofosyne** [comment]
If you want to make a credit page feel free to :)

**Comment by BjornB2** [comment]
Cool thanks for the merge. What do you mean with credit page?

**Comment by mofosyne** [comment]
Just something so we can track who helped out with this project :)

I'm not too sure how it should look. But I'm guessing it could be a `CONTRIBUTOR.txt` page... or I think easier is to just add a new section to the readme called *contributors*.

I should probbly also remember to add virtuaCode's to the readme page as well to thank him for his pull that I merged into my code as well https://github.com/mofosyne/arduino-gameboy-printer-emulator/pull/9

**Comment by mofosyne** [comment]
Actually... I'll do the change myself.

**Comment by mofosyne** [comment]
Done https://github.com/mofosyne/arduino-gameboy-printer-emulator/blob/master/README.md#contributors--thanks

**Comment by BjornB2** [comment]
Cool 😊

**Pull request merged**
