### PR TITLE
Printer reader

### PR DESCRIPTION
**Pull request by tikonen**
Python application that reads data from the printer emulator and writes png files andoptionally raw data log files.

### CODE REVIEW

**Comment by mofosyne** [comment]
I see that this is an extention of the effort of gbpdecoder.py but to add a cli and a way to more easily directly read from the serial port. Nice!

**Comment by mofosyne** [comment]
Looks all good, merging!

**Comment by tikonen** [comment]
Thank you. This has been very convenient app for dumping large number of images from the Gameboy camera.

**Comment by mofosyne** [comment]
Not a problem. Have you also considered cart dumpers? Those would likely be faster, but is certainly more expensive and a little bit more complicated.

**Comment by tikonen** [comment]
True, that would be faster. However our target use case is the personal experience of using GB camera for example in retro party or art exhibition. Then automatically having the image as a souvenir through laser printer, thermal printer or email.

**Comment by tikonen** [comment]
Btw. In case you're interested here is a pic of our emulator. I encased Arduino in army data transfer memory dongle I found at a surplus store 😄 It even had existing busy led I could reuse.

image

**Pull request merged**
