### PR TITLE
Python implementation of decoder

### PR DESCRIPTION
**Pull request by tikonen**
This commit implements python functions and decoder application for the printer emulator data dumps. Functionality is similiar to the  C-code implementation.
Please have a look.
Thanks!

### CODE REVIEW

**Comment by mofosyne** [comment]
Interesting. Did you remember to add yourself to the contributor list at the bottom of the readme? I'll have a look and can commit quick, if it doesn't interact too much with other code. Ideally it should also be self testing using the github actions as well but let's just see how we go.

**Comment by mofosyne** [comment]
This is my test image

2020-08-17_Alice_in_Wonderland_palletsupporttest expected

It looks different from your test data 

test1-2x

I think you are not handling the pallet redefinition correctly.

**Comment by tikonen** [comment]
Hi and thank you for looking into my pull request. Added myself in README.md on the contributor list.
I forgot to enable the palette normalization. Implementation is based on the JS decoder and I don't fully understand how palette normalization works but it should be identical now with that version.
I'm not familiar with Github actions. Later when I've time I may look into that but unfortunately not at this moment.

**Comment by mofosyne** [comment]
Not a problem. Looks all good so far. Thanks for the contribution!

**Pull request merged**
